version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx.prod
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - devops
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mapeando o arquivo nginx.conf
    #   - ./nginx/conf.d:/etc/nginx/conf.d            # Mapeando o diretório de configurações
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: app
    ports:
      - 3000:3000
    networks:
      - devops
    depends_on:
      - nginx
      - db

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_ROOT_PASSWORD=devops
      - MYSQL_DATABASE=devops
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops
      - MYSQL_ROOT_HOST=%   
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - devops
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "devops", "-pdevops", "-e", "SELECT 1"]
      interval: 30s    # Verifica a cada 30 segundos
      timeout: 10s     # Tempo limite para a verificação
      retries: 5       # Tenta 5 vezes antes de considerar que o serviço está inativo

networks:
  devops:
    external: true

volumes:
  mysql-data:
